# Generated by Django 4.2.3 on 2023-11-21 11:38

import blogservice.utils
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0003_alter_user_is_active"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="profile_picture",
            field=models.ImageField(
                blank=True, upload_to=blogservice.utils.uuid_name_upload_to
            ),
        ),
    ]
