# Generated by Django 4.2.3 on 2023-11-21 11:38

import blogservice.utils
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0003_alter_image_file_path_alter_image_post"),
    ]

    operations = [
        migrations.AlterField(
            model_name="image",
            name="file_path",
            field=models.ImageField(upload_to=blogservice.utils.uuid_name_upload_to),
        ),
    ]
